name: 'New Issue Notification'
on:
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        if: env.DISCORD_WEBHOOK_URL != ''
        uses: discord-actions/message@v2
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            # Issue (re)opened on ${{ github.repository }}
            **Creator:** ${{ github.event.issue.user.login }}
            **Link:** [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})